// AUTO-GENERATED by scripts/deploy.sh
export const deploymentsByChain: Record<string, any> = {};
try { deploymentsByChain["1001"] = require("../public/deployments/1001.json"); } catch {}
try { deploymentsByChain["8217"] = require("../public/deployments/8217.json"); } catch {}
export function getDeployments(chainId: number) { return deploymentsByChain[String(chainId)]; }
