[profile.default]
solc_version = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
src = "src"
test = "test"
libs = ["lib"]
via_ir = true
fuzz = { runs = 300 }
# Avoid FFI/env surprises in CI
ffi = false
fs_permissions = []

[rpc_endpoints]
kaia_mainnet = "${KAIA_MAINNET_RPC}"
kaia_testnet = "${KAIA_TESTNET_RPC}"

[etherscan]
kaia_mainnet = { key = "", url = "https://api.kaiascan.io/api" }
kaia_testnet = { key = "", url = "https://api.baobab.kaiascan.io/api" }

[fmt]
line_length = 120